# Generated by Django 5.1.4 on 2025-01-21 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Plugin Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('github_repo_url', models.CharField(max_length=255, unique=True)),
                ('active_version', models.CharField(blank=True, choices=[], max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='app_wp_plugin_server.plugincategory')),
            ],
        ),
        migrations.CreateModel(
            name='PluginVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('file_data', models.BinaryField()),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app_wp_plugin_server.plugin')),
            ],
            options={
                'unique_together': {('plugin', 'version')},
            },
        ),
    ]
