# Generated by Django 5.1.4 on 2025-01-21 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wp_plugin_server', '0002_alter_plugin_active_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('valid_till', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_wp_plugin_server.plugin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
